name: Pull on GitHub Repo Update

on:
  push:
    branches:
      - public  # Adjust this to the branch you want to track

jobs:
  pull_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull latest changes
      run: |
        git pull public public  # Replace 'main' with your branch name
